// SPDX-License-Identifier: Apache-2.0
// Ordered bridge keeps the existing CommonJS and browser modules intact.
import './core/contracts.js';
import './core/period.js';
import './core/identity.js';
import './core/validation.js';
import './core/analysis.js';
import './core/task.js';
import './adapters/storage/memory.js';
import './adapters/import/importer.js';
import './adapters/optional/interfaces.js';
import './core/state.js';
import './core/snapshot.js';
import './adapters/storage/contract.js';
import './adapters/storage/indexeddb.js';
import './core/migration.js';
import './adapters/import/multi.js';
import './core/transactions.js';
import './core/api-registry.js';
import './core/errors.js';
import './core/matching.js';
import './core/client.js';
import * as facade from './core/index.js';
const ScheduleNotesCore = facade.default || globalThis.ScheduleNotesCore;
export default ScheduleNotesCore;
export const createClient = ScheduleNotesCore.createClient;
export const matching = ScheduleNotesCore.matching;
export const schemaVersion = ScheduleNotesCore.schemaVersion;
export const apiVersion = ScheduleNotesCore.apiVersion;
export const apiRegistry = ScheduleNotesCore.apiRegistry;
export const emptyDataset = ScheduleNotesCore.emptyDataset;
export const migrateDataset = ScheduleNotesCore.migrateDataset;
export const validatePeriod = ScheduleNotesCore.validatePeriod;
export const calendarPeriod = ScheduleNotesCore.calendarPeriod;
export const resolveIdentity = ScheduleNotesCore.resolveIdentity;
export const validateRecord = ScheduleNotesCore.validateRecord;
export const validateDataset = ScheduleNotesCore.validateDataset;
export const summarizeSales = ScheduleNotesCore.summarizeSales;
export const createTask = ScheduleNotesCore.createTask;
export const syncActivityTasks = ScheduleNotesCore.syncActivityTasks;
export const importPreview = ScheduleNotesCore.importPreview;
export const commitImport = ScheduleNotesCore.commitImport;
export const createMemoryStore = ScheduleNotesCore.createMemoryStore;
export const optional = ScheduleNotesCore.optional;
export const exportSnapshot = ScheduleNotesCore.exportSnapshot;
export const exportBackup = ScheduleNotesCore.exportBackup;
export const validateSnapshot = ScheduleNotesCore.validateSnapshot;
export const inspectSnapshot = ScheduleNotesCore.inspectSnapshot;
export const restorePreview = ScheduleNotesCore.restorePreview;
export const restoreSnapshot = ScheduleNotesCore.restoreSnapshot;
export const migrationRegistry = ScheduleNotesCore.migrationRegistry;
export const migrationPreview = ScheduleNotesCore.migrationPreview;
export const commitMigration = ScheduleNotesCore.commitMigration;
export const multiImportPreview = ScheduleNotesCore.multiImportPreview;
export const commitMultiImport = ScheduleNotesCore.commitMultiImport;
export const createIndexedDBStore = ScheduleNotesCore.createIndexedDBStore;
export const syncActivityTasksAtomic = ScheduleNotesCore.syncActivityTasksAtomic;
