// SPDX-License-Identifier: Apache-2.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),api=require('../core/index.js'),{generate,scenarios}=require('../generator.cjs');
const issues=(r)=>r.issues.map(x=>x.code);
test('schema 2 fixture validates all eleven collections and provenance',()=>{const f=generate();assert.deepEqual(f,generate());assert.equal(api.validateDataset(f,{requireSynthetic:true}).valid,true);for(const group of ['hospitals','departments','employees','customers','products','sales','employeePlans','activities','tasks','visits','observationPeriods'])for(const r of f[group])assert.equal(r.synthetic,true);});
test('all four matching qualities and hospital-scoped departments',()=>{const f=generate();for(const c of scenarios().matching)assert.equal(api.resolveIdentity(c.entityType,c.query,f).quality,c.expected);assert.equal(api.resolveIdentity('Department',{name:'Synthetic Shared Department'},f).quality,'UNMATCHED');assert.equal(api.resolveIdentity('Department',{id:'D_SYN_001',hospitalId:'H_SYN_002'},f).quality,'UNMATCHED');});
test('probable name has no committed identity and supplied invalid ID never falls back',()=>{const f=generate();assert.equal(api.resolveIdentity('Employee',{name:'Synthetic Employee 1'},f).id,null);assert.equal(api.resolveIdentity('Employee',{id:'E_SYN_UNKNOWN',name:'Synthetic Employee 1'},f).quality,'UNMATCHED');});
test('duplicate stable identity yields AMBIGUOUS and dataset failure',()=>{const f=generate();f.hospitals.push({...f.hospitals[0]});assert.equal(api.resolveIdentity('Hospital',{id:'H_SYN_001'},f).quality,'AMBIGUOUS');assert.ok(issues(api.validateDataset(f)).includes('DUPLICATE_IDENTITY'));});
for(const [label,patch,code] of [
 ['invalid ID',{id:'name as key'},'INVALID_ID'],['impossible date',{eventDate:'2030-02-30'},'INVALID_DATE'],['numeric string',{amount:'30'},'INVALID_NUMERIC_TYPE'],['NaN',{amount:NaN},'INVALID_NUMERIC_TYPE'],['infinity',{amount:Infinity},'INVALID_NUMERIC_TYPE'],['unknown enum',{kind:'estimate'},'INVALID_ENUM'],['sale negative',{amount:-3},'INVALID_NEGATIVE_SEMANTICS'],['return positive',{kind:'return'},'INVALID_RETURN_SEMANTICS'],['missing hospital',{hospitalId:null},'MISSING_HOSPITAL'],['unknown product',{productId:'P_SYN_UNKNOWN'},'UNKNOWN_PRODUCT'],['missing synthetic flag',{synthetic:undefined},'SYNTHETIC_PROVENANCE_REQUIRED'],['unknown field',{inferredAmount:30},'UNKNOWN_FIELD']])
test('validation: '+label,()=>{const f=generate(),row={...f.sales[0],...patch},before=structuredClone(row);assert.ok(issues(api.validateRecord('SalesRecord',row,f,{requireSynthetic:true})).includes(code));assert.deepEqual(row,before);});
test('required fields, nullable amount, zero, and negative return semantics',()=>{const f=generate(),r={...f.sales[0]};delete r.amount;assert.ok(issues(api.validateRecord('SalesRecord',r,f)).includes('MISSING_REQUIRED_FIELD'));assert.equal(api.validateRecord('SalesRecord',f.sales[3],f).valid,true);assert.equal(api.validateRecord('SalesRecord',f.sales[1],f).valid,true);assert.equal(api.validateRecord('SalesRecord',f.sales[2],f).valid,true);});
test('same-named customer cannot cross department hospital namespace',()=>{const f=generate(),customer={...f.customers[0],departmentId:'D_SYN_002'};assert.ok(issues(api.validateRecord('Customer',customer,f)).includes('UNKNOWN_DEPARTMENT'));});
test('malformed arrays fail without throwing; cross-hospital activity fails',()=>{const f=generate();assert.ok(!api.validateRecord('Activity',{...f.activities[0],customerIds:3},f).valid);assert.ok(issues(api.validateRecord('Activity',{...f.activities[0],customerIds:['C_SYN_002']},f)).includes('CROSS_HOSPITAL_RELATION'));});
test('event/plan/observation/report periods cannot interchange',()=>{const plan=generate().employeePlans[0].planPeriod;assert.equal(api.validatePeriod(plan,'plan').valid,true);assert.equal(api.validatePeriod(plan,'report').valid,false);assert.equal(api.validatePeriod({kind:'report',from:'2030-10-02',to:'2030-10-01'}).valid,false);assert.equal(api.calendarPeriod({periodFor:()=>plan},'2030-10-01','plan').valid,true);assert.equal(api.calendarPeriod({periodFor:()=>plan},'2030-10-01','report').valid,false);});
test('schema migration never silently fabricates v1 provenance or period roles',()=>{const f=generate();assert.equal(api.migrateDataset(f).dataset,f);assert.equal(api.migrateDataset({schemaVersion:1},2).status,'MIGRATION_REQUIRED_MANUAL');assert.equal(api.validateDataset({schemaVersion:99}).valid,false);});
test('new activity API handles draft, cancelled and completed without duplicates',()=>{const f=generate();assert.equal(api.syncActivityTasks(f.activities[1],[],f).tasks.length,0);const first=api.syncActivityTasks(f.activities[0],[],f);assert.equal(first.tasks.length,3);assert.deepEqual(api.syncActivityTasks(f.activities[0],first.tasks,f).tasks,first.tasks);assert.ok(api.syncActivityTasks(f.activities[2],[],f).tasks.length===0);const cancelled=api.syncActivityTasks({...f.activities[0],approval:'cancelled'},first.tasks,f);assert.ok(cancelled.tasks.every(t=>t.status==='cancelled'));assert.ok(api.syncActivityTasks(f.activities[3],[],f).tasks.every(t=>t.status==='done'));});
test('task API rejects duplicate IDs and invalid data; activity rejects malformed task store',()=>{const f=generate();assert.equal(api.createTask(f.tasks[0],f).status,'INVALID_INPUT');assert.equal(api.createTask({...f.tasks[0],id:'T_SYN_NEW'},f).status,'VALID');assert.equal(api.syncActivityTasks(f.activities[0],[f.tasks[0],f.tasks[0]],f).status,'INVALID_INPUT');});
test('optional adapters are interfaces only and core works without providers',()=>{assert.equal(api.optional.aiProvider({analyze(){},suggest(){}}).valid,true);assert.equal(api.optional.aiProvider(null).valid,false);assert.equal(api.optional.excelReader({}).valid,false);assert.equal(api.validateDataset(generate()).valid,true);});

test('invalid collection and prototype entity type return statuses; missing context is not valid',()=>{assert.equal(api.resolveIdentity('Hospital',{id:'H_SYN_001'},{hospitals:'not an array'}).code,'INVALID_IDENTITY_COLLECTION');assert.equal(api.resolveIdentity('toString',{},generate()).code,'UNKNOWN_ENTITY_TYPE');assert.equal(api.validateRecord('__proto__',{},generate()).valid,false);assert.ok(issues(api.validateRecord('SalesRecord',generate().sales[0])).includes('MISSING_DATASET_CONTEXT'));});
