// SPDX-License-Identifier: Apache-2.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const c=require('../core/core.js'),{generate}=require('../fixtures/synthetic/legacy.cjs');
test('fixture determinism and original synthetic identities',()=>{const f=generate();assert.deepEqual(f,generate());assert.equal(f.synthetic,true);for(const group of ['hospitals','departments','employees','customers','products','sales','employeePlans','activities','manualTasks'])for(const row of f[group])assert.equal(row.synthetic,true);assert.equal(f.customers[0].customerName,f.customers[1].customerName);assert.notEqual(f.customers[0].customerId,f.customers[1].customerId);});
test('cross-source relations are stable IDs',()=>{const f=generate();const has=(group,key,value)=>f[group].some(r=>r[key]===value);for(const x of f.customers){assert.ok(has('hospitals','hospitalId',x.hospitalId));assert.ok(has('departments','departmentId',x.departmentId));}for(const x of f.sales){if(x.hospitalId!==null)assert.ok(has('hospitals','hospitalId',x.hospitalId));assert.ok(has('products','productId',x.productId));assert.ok(has('employees','employeeId',x.employeeId));}for(const a of f.activities)for(const id of a.customerIds)assert.ok(has('customers','customerId',id));});
test('approval creates three unique tasks, sync is idempotent',()=>{const a=generate().activities[0],t=c.activityTasks(a);assert.equal(t.length,3);assert.equal(new Set(t.map(x=>x.id)).size,3);assert.deepEqual(c.activityTasks(a,t),t);});
test('draft creates none; cancellation preserves task records',()=>{const a=generate().activities[0];assert.deepEqual(c.activityTasks({...a,approvalStatus:'草稿'}),[]);const t=c.activityTasks({...a,approvalStatus:'已取消'},c.activityTasks(a));assert.equal(t.length,3);assert.ok(t.every(x=>x.status==='cancelled'));});
test('visit deduplication uses customer and product IDs, excludes terminal states',()=>{const first=c.visitTask('C_SYN_001','P_SYN_001','2030-10-01');assert.equal(c.visitTask('C_SYN_001','P_SYN_001','2030-10-02',[first]),first);assert.notEqual(c.visitTask('C_SYN_002','P_SYN_001','2030-10-01',[first]).id,first.id);assert.notEqual(c.visitTask('C_SYN_001','P_SYN_002','2030-10-01',[first]).id,first.id);assert.equal(c.visitTask('C_SYN_001','P_SYN_001','2030-10-02',[{...first,status:'done'}]).dueDate,'2030-10-02');});
test('dates reject impossible days; leap dates work',()=>{assert.equal(c.validDate('2030-02-30'),false);assert.equal(c.validDate('2032-02-29'),true);assert.throws(()=>c.visitTask('C','P','2030-02-30'));assert.throws(()=>c.salesSummary([],{from:'2030-11-01',to:'2030-10-01'}));});
test('period and product filtering distinguish missing from zero and returns',()=>{const rows=generate().sales;const q={productId:'P_SYN_001',from:'2030-10-01',to:'2030-10-03'};assert.equal(c.salesSummary(rows,q).salesAmount,15);assert.equal(c.salesSummary(rows,{...q,productId:'P_SYN_002'}).salesAmount,0);assert.equal(c.salesSummary(rows,{...q,to:'2030-10-31'}).salesAmount,null);assert.equal(c.salesSummary(rows,{...q,to:'2030-10-31'}).truth,'INCOMPLETE');assert.equal(c.salesSummary(rows,{...q,from:'2030-09-01',to:'2030-09-30'}).truth,'NO_DATA');});
test('persistence verifies exact readback and propagates quota failures',()=>{const m=new Map(),storage={getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,v)},s=c.createStore(storage);assert.equal(s.load(),null);s.save({synthetic:true,tasks:[]});assert.deepEqual(s.load(),{synthetic:true,tasks:[]});assert.throws(()=>c.createStore({getItem:()=>null,setItem:()=>{}}).save({}),/readback/);assert.throws(()=>c.createStore({getItem:()=>null,setItem:()=>{throw Error('quota');}}).save({}),/quota/);});
