// SPDX-License-Identifier: Apache-2.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),api=require('../core/index.js'),{parseCSV}=require('../adapters/import/importer.js'),{generate}=require('../generator.cjs');
const fresh=()=>generate(),withoutSource=r=>{const {source,...x}=r;return x;};
const row=()=>({...withoutSource(fresh().sales[0]),id:'S_SYN_NEW'});
const preview=(dataset,text,extra={})=>api.importPreview({dataset,text,format:'json',entityType:'SalesRecord',sourceId:'SRC_SYN_IMPORT',batchId:'BATCH_SYN_001',...extra});
test('CSV parses quoted comma, escaped quote, multiline and CRLF',()=>{const r=parseCSV('id,title\r\nT_SYN_1,"A, ""quoted""\nline"\r\n');assert.deepEqual(r.issues,[]);assert.equal(r.rows[0].title,'A, "quoted"\nline');});
test('CSV rejects malformed quotes, duplicate headers and column counts',()=>{assert.equal(parseCSV('id,id\nx,y').issues[0].code,'DUPLICATE_OR_EMPTY_HEADER');assert.equal(parseCSV('id,x\n"A"oops,y').issues[0].code,'INVALID_CSV_AFTER_QUOTE');assert.equal(parseCSV('id,x\n"A,y').issues[0].code,'UNTERMINATED_CSV_QUOTE');assert.equal(parseCSV('id,x\nA').issues[0].code,'CSV_COLUMN_COUNT');});
test('preview never writes, commit persists exact provenance and batch fingerprint',async()=>{const f=fresh(),before=structuredClone(f),p=await preview(f,JSON.stringify([row()]));assert.equal(p.status,'READY');assert.deepEqual(p.counts,{valid:1,invalid:0,duplicate:0,ambiguous:0,unmatched:0,ignored:0});assert.deepEqual(f,before);assert.ok(Object.isFrozen(p.actions[0].row));const store=api.createMemoryStore(f);assert.equal((await store.read()).sales.length,4);assert.equal((await api.commitImport(p,store)).status,'COMMITTED');const next=await store.read();assert.equal(next.sales.length,5);assert.equal(next.sales[4].source.fingerprint,p.fingerprint);assert.equal(next.sales[4].source.batchId,'BATCH_SYN_001');assert.equal(next.importBatches[0].synthetic,true);});
test('same bytes are repeated import; different formatting cannot duplicate same facts',async()=>{const store=api.createMemoryStore(fresh()),text=JSON.stringify([row()]);let p=await preview(await store.read(),text);await api.commitImport(p,store);p=await preview(await store.read(),text,{batchId:'BATCH_SYN_002'});assert.equal(p.status,'REPEATED_IMPORT');assert.equal((await api.commitImport(p,store)).status,'NO_CHANGE');p=await preview(await store.read(),JSON.stringify([row()],null,2),{batchId:'BATCH_SYN_003'});assert.equal(p.counts.duplicate,1);assert.equal(p.counts.ignored,1);await api.commitImport(p,store);assert.equal((await store.read()).sales.length,5);});
test('duplicate input is deduplicated; conflicting duplicate input blocks both',async()=>{let p=await preview(fresh(),JSON.stringify([row(),row()]));assert.equal(p.counts.valid,1);assert.equal(p.counts.duplicate,1);p=await preview(fresh(),JSON.stringify([row(),{...row(),amount:999}]));assert.equal(p.status,'BLOCKED');assert.equal(p.counts.valid,0);assert.equal(p.counts.invalid,2);});
test('updates need explicit policy; absence never deletes',async()=>{const f=fresh(),changed={...withoutSource(f.sales[0]),amount:17};let p=await preview(f,JSON.stringify([changed]));assert.equal(p.status,'BLOCKED');p=await preview(f,JSON.stringify([changed]),{policy:{updates:'replace',deletes:'reject'}});const store=api.createMemoryStore(f);assert.equal((await api.commitImport(p,store)).status,'COMMITTED');assert.equal((await store.read()).sales.length,4);assert.equal((await store.read()).sales[0].amount,17);});
test('explicit deletion works for unreferenced facts but referenced entity deletion fails preview',async()=>{const f=fresh(),del={id:f.sales[0].id,synthetic:true,operation:'delete'};let p=await preview(f,JSON.stringify([del]));assert.equal(p.status,'BLOCKED');p=await preview(f,JSON.stringify([del]),{policy:{updates:'reject',deletes:'explicit'}});const store=api.createMemoryStore(f);await api.commitImport(p,store);assert.equal((await store.read()).sales.length,3);p=await preview(f,JSON.stringify([{id:'H_SYN_001',synthetic:true,operation:'delete'}]),{entityType:'Hospital',policy:{updates:'reject',deletes:'explicit'}});assert.equal(p.status,'BLOCKED');assert.ok(p.issues.some(x=>x.code==='PROJECTED_DATASET_INVALID'));});
test('stale or tampered preview cannot write and store snapshots cannot mutate storage',async()=>{const store=api.createMemoryStore(fresh()),p=await preview(await store.read(),JSON.stringify([row()])),copy=structuredClone(p);copy.actions[0].row.amount=88;assert.equal((await api.commitImport(copy,store)).status,'TAMPERED_PREVIEW');const snap=await store.read();snap.sales[0].amount=77;assert.equal((await store.read()).sales[0].amount,30);await api.commitImport(p,store);assert.equal((await api.commitImport(p,store)).status,'STALE_PREVIEW');});
test('concurrent commits compare and swap; exactly one wins',async()=>{const store=api.createMemoryStore(fresh()),base=await store.read(),p1=await preview(base,JSON.stringify([row()])),p2=await preview(base,JSON.stringify([{...row(),id:'S_SYN_OTHER'}]),{batchId:'BATCH_SYN_002'});const results=await Promise.all([api.commitImport(p1,store),api.commitImport(p2,store)]);assert.equal(results.filter(x=>x.status==='COMMITTED').length,1);assert.equal((await store.read()).sales.length,5);});
test('unknown stable references block preview and never bind by display name',async()=>{const p=await preview(fresh(),JSON.stringify([{...row(),productId:'P_SYN_UNKNOWN'}]));assert.equal(p.status,'BLOCKED');assert.equal(p.counts.unmatched,1);});
test('name-only ambiguous and probable candidates are reported, never committed',async()=>{const f=fresh(),visit=withoutSource(f.visits[0]);delete visit.customerId;visit.customerName='Synthetic Same Name';let p=await preview(f,JSON.stringify([visit]),{entityType:'Visit'});assert.equal(p.counts.ambiguous,1);assert.equal(p.matching[0].quality,'AMBIGUOUS');assert.equal(p.status,'BLOCKED');delete visit.customerName;visit.customerId='C_SYN_001';delete visit.employeeId;visit.employeeName='Synthetic Employee 1';p=await preview(f,JSON.stringify([visit]),{entityType:'Visit'});assert.equal(p.matching[0].quality,'PROBABLE');assert.equal(p.status,'BLOCKED');});
test('CSV explicit numeric/null conversions appear in preview; no silent coercion',async()=>{const headers='id,hospitalId,employeeId,productId,eventDate,netQuantity,amount,kind,synthetic\n',values='S_SYN_CSV,H_SYN_001,E_SYN_001,P_SYN_001,2030-10-01,0,,sale,true';let p=await preview(fresh(),headers+values,{format:'csv'});assert.equal(p.status,'READY');assert.equal(p.actions[0].row.amount,null);assert.ok(p.normalizations.some(x=>x.code==='EXPLICIT_NULL'));p=await preview(fresh(),headers+values.replace(',0,,',',1e3,0,'),{format:'csv'});assert.equal(p.status,'BLOCKED');assert.ok(p.issues.some(x=>x.code==='INVALID_NUMERIC_TOKEN'));});
test('bad JSON, schema, format, private provenance and missing synthetic fail',async()=>{for(const [text,extra] of [['{',{}],['{}',{}],['[]',{format:'xlsx'}],[JSON.stringify([{...row(),synthetic:false}]),{}],[JSON.stringify([{...row(),source:{sourceId:'SRC_SYN_CLAIMED'}}]),{}]])assert.equal((await preview(fresh(),text,extra)).status,'BLOCKED');});
test('batch ID cannot be reused for a different fingerprint',async()=>{const store=api.createMemoryStore(fresh());await api.commitImport(await preview(await store.read(),JSON.stringify([row()])),store);const p=await preview(await store.read(),JSON.stringify([{...row(),id:'S_SYN_OTHER'}]));assert.ok(p.issues.some(x=>x.code==='BATCH_ID_CONFLICT'));});

test('blocked preview cannot be re-labelled READY to commit a valid subset',async()=>{const f=fresh(),p=await preview(f,JSON.stringify([row(),{...row(),id:'S_SYN_BAD',amount:'bad'}])),tampered=structuredClone(p),store=api.createMemoryStore(f);assert.equal(p.status,'BLOCKED');tampered.status='READY';assert.equal((await api.commitImport(tampered,store)).status,'PREVIEW_NOT_READY');tampered.issues=[];assert.equal((await api.commitImport(tampered,store)).status,'TAMPERED_PREVIEW');assert.equal((await store.read()).sales.length,4);});
test('invalid batch provenance or hidden dataset fields block import context',async()=>{const f=fresh();f.importBatches=[null];assert.equal((await preview(f,'[]')).status,'BLOCKED');const f2=fresh();f2.unknownFacts=[];assert.equal((await preview(f2,'[]')).status,'BLOCKED');});

test('false/empty operations or policies are errors, not default-normalized',async()=>{for(const operation of ['',false,0])assert.equal((await preview(fresh(),JSON.stringify([{...row(),operation}]))).status,'BLOCKED');for(const policy of [null,{updates:false},{updates:''},{extra:'guess'}])assert.equal((await preview(fresh(),'[]',{policy})).status,'BLOCKED');assert.equal((await preview(fresh(),'[]',{entityType:'__proto__'})).status,'BLOCKED');});
