// SPDX-License-Identifier: Apache-2.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),api=require('../core/index.js'),{generate}=require('../generator.cjs'),{memoryAdapter}=require('../adapters/storage/contract.js'),{schema1,multiFiles}=require('../fixtures/synthetic/reliability.cjs');
test('atomic Activity-to-Task sync commits activity and all tasks together',async()=>{const store=api.createMemoryStore(generate()),activity={...(await store.read()).activities[0],title:'Synthetic Changed Activity'},result=await api.syncActivityTasksAtomic(activity,store);assert.equal(result.status,'COMPLETE');const current=await store.read();assert.equal(current.activities[0].id==='A_SYN_001'?current.activities[0].title:current.activities.at(-1).title,activity.title);assert.equal(current.tasks.filter(x=>x.activityId===activity.id).length,3);assert.ok(current.tasks.filter(x=>x.activityId===activity.id).every(x=>x.title.includes(activity.title)));});
test('activity commit failure never reports success and leaves activity/tasks intact',async()=>{let fail=false;const store=memoryAdapter(generate(),{beforeCommit:()=>{if(fail)throw Error('Synthetic write failure');}}),before=await store.read();fail=true;const result=await api.syncActivityTasksAtomic({...before.activities[0],title:'Synthetic Changed'},store);assert.equal(result.status,'FAILED');assert.equal(result.taskCount,null);assert.deepEqual(await store.read(),before);});
test('invalid activity and ID collision rollback rather than leave partial tasks',async()=>{const store=api.createMemoryStore(generate()),before=await store.read();assert.equal((await api.syncActivityTasksAtomic({...before.activities[0],hospitalId:'H_SYN_MISSING'},store)).status,'FAILED');assert.deepEqual(await store.read(),before);});
test('completed and cancelled task states survive repeated activity sync',async()=>{const store=api.createMemoryStore(generate()),activity=generate().activities[0];await api.syncActivityTasksAtomic(activity,store);await store.transaction(d=>{d.tasks.find(x=>x.kind==='prepare').status='done';d.tasks.find(x=>x.kind==='review').status='cancelled';});await api.syncActivityTasksAtomic(activity,store);const tasks=await store.list('Task');assert.equal(tasks.find(x=>x.kind==='prepare').status,'done');assert.equal(tasks.find(x=>x.kind==='review').status,'cancelled');});
test('migration, import, snapshot and output run through only the public API',async()=>{const store=api.createMemoryStore(api.emptyDataset());await api.commitMigration(await api.migrationPreview(schema1(),{targetDataset:await store.read()}),store);const plan=await api.multiImportPreview({dataset:await store.read(),files:multiFiles(),sourceId:'SRC_SYN_FLOW',batchId:'BATCH_SYN_FLOW'});assert.equal(plan.status,'READY');await api.commitMultiImport(plan,store);const snapshot=await store.snapshot(),reopened=api.createMemoryStore(api.emptyDataset());await reopened.restore(snapshot);const options={productId:'P_SYN_001',period:{kind:'report',from:'2030-10-01',to:'2030-10-04'}};assert.deepEqual(api.summarizeSales(await reopened.read(),options),api.summarizeSales(await store.read(),options));});
test('output completeness and null/zero semantics remain unchanged across restore',async()=>{const store=api.createMemoryStore(generate()),snapshot=await store.snapshot(),copy=api.createMemoryStore(api.emptyDataset());await copy.restore(snapshot);for(const to of ['2030-10-03','2030-10-04','2030-10-31']){const query={productId:'P_SYN_001',period:{kind:'report',from:'2030-10-01',to}};assert.deepEqual(api.summarizeSales(await copy.read(),query),api.summarizeSales(generate(),query));}});
test('unrelated task colliding with generated activity ID rolls back Activity and Task together',async()=>{const data=generate();data.tasks.push({...data.tasks[0],id:'A_SYN_001_PREPARE'});const store=api.createMemoryStore(data),before=await store.read(),result=await api.syncActivityTasksAtomic({...data.activities[0],title:'Synthetic New Title'},store);assert.equal(result.status,'FAILED');assert.deepEqual(await store.read(),before);});
