// SPDX-License-Identifier: Apache-2.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),api=require('../core/index.js'),{schema1}=require('../fixtures/synthetic/reliability.cjs'),{generate}=require('../generator.cjs');
test('schema 1 dry-run is deterministic, preserves IDs, null/zero and explicit period roles',async()=>{const source=schema1(),before=structuredClone(source),a=await api.migrationPreview(source),b=await api.migrationPreview(source);assert.equal(a.status,'READY');assert.deepEqual(a.dataset,b.dataset);assert.deepEqual(source,before);assert.equal(a.dataset.sales[3].amount,null);assert.equal(a.dataset.sales[1].amount,0);assert.equal(a.dataset.sales[0].id,source.sales[0].id);assert.equal(a.dataset.employeePlans[0].planPeriod.kind,'plan');assert.equal(a.dataset.observationPeriods[0].kind,'observation');assert.equal(a.backup.records.schemaVersion,1);});
test('migration commits atomically, records version and is idempotent',async()=>{const store=api.createMemoryStore(api.emptyDataset()),plan=await api.migrationPreview(schema1(),{targetDataset:await store.read()}),result=await api.commitMigration(plan,store);assert.equal(result.status,'COMMITTED');assert.equal(result.fromVersion,1);assert.equal(result.toVersion,2);assert.equal(result.counts.read,24);const next=await api.migrationPreview(await store.read(),{targetDataset:await store.read()});assert.equal(next.status,'NO_CHANGE');assert.equal((await api.commitMigration(next,store)).status,'COMMITTED');});
test('migration requires target revision; source-only planning never overwrites storage',async()=>{const store=api.createMemoryStore(generate()),before=await store.read();assert.equal((await api.commitMigration(await api.migrationPreview(schema1()),store)).status,'TARGET_CONTEXT_REQUIRED');assert.deepEqual(await store.read(),before);});
test('invalid migration remains recoverable and never writes a partial subset',async()=>{const store=api.createMemoryStore(generate()),source=schema1(),before=await store.read();source.sales[0].hospitalId=null;const plan=await api.migrationPreview(source,{targetDataset:before});assert.equal(plan.status,'BLOCKED');assert.equal(plan.dataset,null);assert.equal(plan.backup.records.sales[0].hospitalId,null);assert.equal((await api.commitMigration(plan,store)).status,'PREVIEW_NOT_READY');assert.deepEqual(await store.read(),before);});
test('legacy unknown fields, absent collections and unknown enums reject rather than disappear',async()=>{for(const change of [d=>{d.sales[0].newField=1;},d=>{delete d.customers;},d=>{d.tasks[0].status='odd';},d=>{d.employeePlans[0].month='2030-13';}]){const source=schema1();change(source);assert.equal((await api.migrationPreview(source)).status,'BLOCKED');}});
test('future schema and invalid snapshot checksum cannot migrate',async()=>{assert.equal((await api.migrationPreview({...schema1(),schemaVersion:3})).status,'BLOCKED');const snapshot=structuredClone(await api.exportSnapshot(generate()));snapshot.records.sales[0].amount=13;assert.equal((await api.migrationPreview(snapshot)).status,'BLOCKED');});
test('tampered or stale migration plans never overwrite',async()=>{const store=api.createMemoryStore(generate()),plan=await api.migrationPreview(schema1(),{targetDataset:await store.read()}),tampered=structuredClone(plan);tampered.dataset.sales[0].amount=99;assert.equal((await api.commitMigration(tampered,store)).status,'TAMPERED_PREVIEW');await store.delete('SalesRecord','S_SYN_002');assert.equal((await api.commitMigration(plan,store)).status,'STALE_PREVIEW');});
test('explicit dates are required; migration cannot infer events from timestamp text',async()=>{const source=schema1();delete source.activities[0].eventDate;source.activities[0].startTime='2030-10-05T10:00';assert.equal((await api.migrationPreview(source)).status,'BLOCKED');});
test('damaged schema 2 input returns a blocked plan without throwing',async()=>{const source=generate();delete source.sales;const plan=await api.migrationPreview(source);assert.equal(plan.status,'BLOCKED');assert.equal(plan.dataset,null);assert.ok(plan.errors.some(x=>x.code==='MISSING_COLLECTION'));});
test('explicit historical leap month maps without 1900-century date coercion',async()=>{const source=schema1();source.employeePlans[0].month='0000-02';const plan=await api.migrationPreview(source);assert.equal(plan.status,'READY');assert.equal(plan.dataset.employeePlans[0].planPeriod.to,'0000-02-29');});
