// SPDX-License-Identifier: Apache-2.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),api=require('../core/index.js'),u=require('../core/state.js'),{generate}=require('../generator.cjs'),{multiFiles}=require('../fixtures/synthetic/reliability.cjs');
const context=(dataset=api.emptyDataset(),files=multiFiles(),batchId='BATCH_SYN_MULTI')=>({dataset,files,sourceId:'SRC_SYN_MULTI',batchId});
test('multi-entity import resolves reference entities before facts despite file order',async()=>{const store=api.createMemoryStore(api.emptyDataset()),plan=await api.multiImportPreview(context(await store.read()));assert.equal(plan.status,'READY');assert.equal(plan.counts.CREATE,18);assert.equal((await api.commitMultiImport(plan,store)).status,'COMMITTED');assert.equal((await store.read()).sales.length,4);assert.equal((await store.read()).customers[0].departmentId,'D_SYN_001');});
test('same file batch after restart-equivalent store reload adds zero facts',async()=>{const store=api.createMemoryStore(api.emptyDataset());await api.commitMultiImport(await api.multiImportPreview(context(await store.read())),store);const persisted=await store.read(),reopened=api.createMemoryStore(persisted),plan=await api.multiImportPreview(context(await reopened.read(),multiFiles(),'BATCH_SYN_AGAIN'));assert.equal(plan.status,'REPEATED_IMPORT');assert.equal(plan.counts.CREATE,0);assert.equal(plan.counts.DUPLICATE,18);assert.equal((await api.commitMultiImport(plan,reopened)).status,'NO_CHANGE');});
test('cross-file equal facts remain unchanged rather than duplicated',async()=>{const files=multiFiles();files[0].text=JSON.stringify(JSON.parse(files[0].text),null,2);const plan=await api.multiImportPreview(context(generate(),files));assert.equal(plan.status,'READY');assert.equal(plan.counts.UNCHANGED,18);assert.equal(plan.counts.CREATE,0);});
test('cross-file changed fact is a conflict with existing/incoming/reason',async()=>{const files=multiFiles(),rows=JSON.parse(files[0].text);rows[0].amount=17;files[0].text=JSON.stringify(rows);const plan=await api.multiImportPreview(context(generate(),files));assert.equal(plan.status,'BLOCKED');const conflict=plan.results.find(x=>x.outcome==='CONFLICT');assert.equal(conflict.existing.amount,30);assert.equal(conflict.incoming.amount,17);assert.equal(conflict.reason[0].code,'EXPLICIT_UPDATE_FINGERPRINT_REQUIRED');});
test('explicit reviewed update requires fingerprint of the exact existing fact',async()=>{const data=generate(),files=multiFiles(),rows=JSON.parse(files[0].text);rows[0].amount=17;files[0].text=JSON.stringify(rows);const {source,...existing}=data.sales[0],plan=await api.multiImportPreview({...context(data,files),updates:[{entityType:'SalesRecord',id:existing.id,expectedFingerprint:await u.hash(existing)}]});assert.equal(plan.status,'READY');assert.equal(plan.counts.UPDATE,1);const store=api.createMemoryStore(data);assert.equal((await api.commitMultiImport(plan,store)).status,'COMMITTED');assert.equal((await store.read()).sales[0].amount,17);});
test('same input row is DUPLICATE; different input with same ID blocks all copies',async()=>{let files=multiFiles();files.push({...files[0],name:'Synthetic duplicate.json'});let plan=await api.multiImportPreview(context(api.emptyDataset(),files));assert.equal(plan.counts.DUPLICATE,4);files=multiFiles();const changed={...JSON.parse(files[0].text)[0],amount:12};files.push({...files[0],name:'Synthetic conflict.json',text:JSON.stringify([changed])});plan=await api.multiImportPreview(context(api.emptyDataset(),files));assert.equal(plan.status,'BLOCKED');assert.equal(plan.counts.CONFLICT,2);});
test('broken references and same-name candidates never guess a first match',async()=>{const files=multiFiles(),rows=JSON.parse(files[1].text);rows[0].departmentId='D_SYN_MISSING';delete rows[1].hospitalId;rows[1].hospitalName='Synthetic Hospital 2';files[1].text=JSON.stringify(rows);const plan=await api.multiImportPreview(context(api.emptyDataset(),files));assert.equal(plan.status,'BLOCKED');assert.ok(plan.counts.REJECT>=2);assert.equal(plan.nextDataset,null);});
test('mixed valid/invalid rows cannot commit a partial import',async()=>{const files=multiFiles(),rows=JSON.parse(files[0].text);rows[0].amount='bad';files[0].text=JSON.stringify(rows);const store=api.createMemoryStore(api.emptyDataset()),before=await store.read(),plan=await api.multiImportPreview(context(before,files));assert.equal((await api.commitMultiImport(plan,store)).status,'PREVIEW_NOT_READY');assert.deepEqual(await store.read(),before);});
test('tampered and stale multi previews cannot write',async()=>{const store=api.createMemoryStore(api.emptyDataset()),plan=await api.multiImportPreview(context(await store.read())),tampered=structuredClone(plan);tampered.nextDataset.sales[0].amount=99;assert.equal((await api.commitMultiImport(tampered,store)).status,'TAMPERED_PREVIEW');await api.commitMultiImport(plan,store);assert.equal((await api.commitMultiImport(plan,store)).status,'STALE_PREVIEW');});
test('batch ID collision, reserved provenance and unknown entity reject',async()=>{const store=api.createMemoryStore(api.emptyDataset());await api.commitMultiImport(await api.multiImportPreview(context(await store.read())),store);const files=multiFiles();files[0].text+=' ';assert.equal((await api.multiImportPreview(context(await store.read(),files))).status,'BLOCKED');const unknown=multiFiles();unknown[0].entityType='__proto__';assert.equal((await api.multiImportPreview(context(api.emptyDataset(),unknown))).status,'BLOCKED');});
test('row, file, source and batch fingerprints survive atomic commit',async()=>{const store=api.createMemoryStore(api.emptyDataset()),plan=await api.multiImportPreview(context(await store.read()));assert.match(plan.results[0].rowFingerprint,/^[a-f0-9]{64}$/);await api.commitMultiImport(plan,store);const row=(await store.read()).sales[0];assert.equal(row.source.sourceId,'SRC_SYN_MULTI');assert.equal(row.source.batchId,'BATCH_SYN_MULTI');assert.ok(plan.fileFingerprints.includes(row.source.fingerprint));});
test('CSV multi import performs explicit numeric and null conversion',async()=>{const file={name:'Synthetic sale.csv',format:'csv',entityType:'SalesRecord',text:'id,hospitalId,employeeId,productId,eventDate,netQuantity,amount,kind,synthetic\nS_SYN_CSV,H_SYN_001,E_SYN_001,P_SYN_001,2030-10-01,0,,sale,true'},plan=await api.multiImportPreview(context(generate(),[file]));assert.equal(plan.status,'READY');assert.equal(plan.nextDataset.sales.at(-1).amount,null);assert.equal(plan.nextDataset.sales.at(-1).netQuantity,0);});
test('duplicate update resolutions and reused batch with another source cannot choose first match',async()=>{const data=generate(),{source,...existing}=data.sales[0],resolution={entityType:'SalesRecord',id:existing.id,expectedFingerprint:await u.hash(existing)};assert.equal((await api.multiImportPreview({...context(data),updates:[resolution,resolution]})).status,'BLOCKED');const store=api.createMemoryStore(api.emptyDataset());await api.commitMultiImport(await api.multiImportPreview(context(await store.read())),store);const plan=await api.multiImportPreview({...context(await store.read()),sourceId:'SRC_SYN_OTHER'});assert.equal(plan.status,'BLOCKED');assert.ok(plan.issues.some(x=>x.code==='BATCH_ID_CONFLICT'));});
