// SPDX-License-Identifier: Apache-2.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),api=require('../core/index.js'),{generate}=require('../generator.cjs');
const q=(from='2030-10-01',to='2030-10-03',productId='P_SYN_001')=>({productId,period:{kind:'report',from,to}});
test('output explains source, object, period, calculation, matching and completeness',()=>{const r=api.summarizeSales(generate(),q());assert.equal(r.value,24);assert.equal(r.truthStatus,'COMPLETE');assert.deepEqual(r.source.sourceIds,['SRC_SYN_001']);assert.equal(r.entity.id,'P_SYN_001');assert.equal(r.period.kind,'report');assert.equal(r.matchingQuality,'EXACT');assert.deepEqual(r.calculation.recordIds,['S_SYN_001','S_SYN_003']);assert.equal(r.completeness.coverage,'COMPLETE');});
test('missing remains null, true zero remains zero, returns remain negative',()=>{const f=generate();assert.equal(api.summarizeSales(f,q('2030-10-01','2030-10-04')).value,null);assert.equal(api.summarizeSales(f,q('2030-10-01','2030-10-04')).truthStatus,'INCOMPLETE');assert.equal(api.summarizeSales(f,q('2030-10-02','2030-10-02','P_SYN_002')).value,0);assert.equal(api.summarizeSales(f,q('2030-10-03','2030-10-03')).value,-6);});
test('no data is NO_DATA and not a zero observation',()=>{const r=api.summarizeSales(generate(),q('2030-09-01','2030-09-30'));assert.equal(r.value,null);assert.equal(r.truthStatus,'NO_DATA');});
test('observation gap prevents a complete-looking sum',()=>{const f=generate();f.sales=[f.sales[0]];const r=api.summarizeSales(f,q('2030-10-01','2030-10-31'));assert.equal(r.value,null);assert.ok(r.limitations.includes('OBSERVATION_PERIOD_GAP'));});
test('every selected source needs its own observation coverage',()=>{const f=generate();f.sales[2].source={sourceId:'SRC_SYN_002'};const r=api.summarizeSales(f,q());assert.equal(r.value,null);assert.equal(r.completeness.coverage,'GAP_OR_UNKNOWN');});
test('duplicate facts invalidate sums; ambiguous or missing identity stays explicit',()=>{const f=generate();f.sales.push({...f.sales[0]});assert.ok(api.summarizeSales(f,q()).limitations.includes('DUPLICATE_RECORD'));f.sales.pop();f.hospitals.push({...f.hospitals[0]});assert.equal(api.summarizeSales(f,q()).truthStatus,'AMBIGUOUS');f.hospitals.pop();f.sales[0].hospitalId=null;assert.equal(api.summarizeSales(f,q()).truthStatus,'UNMATCHED');});
test('invalid event date is not silently filtered into a complete total',()=>{const f=generate();f.sales[0].eventDate='2030-02-30';const r=api.summarizeSales(f,q());assert.equal(r.value,null);assert.ok(r.limitations.includes('INVALID_DATE'));});
test('plan periods and unknown products cannot be coerced into observations',()=>{const f=generate();assert.equal(api.summarizeSales(f,{productId:'P_SYN_001',period:f.employeePlans[0].planPeriod}).truthStatus,'INVALID_INPUT');assert.equal(api.summarizeSales(f,q('2030-10-01','2030-10-03','P_SYN_UNKNOWN')).truthStatus,'UNMATCHED');});
test('numeric overflow is a limitation instead of an infinite fact',()=>{const f=generate();f.sales=f.sales.slice(0,1);f.sales[0].amount=Number.MAX_VALUE;f.sales.push({...f.sales[0],id:'S_SYN_OVERFLOW'});const r=api.summarizeSales(f,q());assert.equal(r.value,null);assert.ok(r.limitations.includes('CALCULATION_OVERFLOW'));});
