// SPDX-License-Identifier: Apache-2.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),api=require('../core/index.js'),u=require('../core/state.js'),{generate}=require('../generator.cjs'),{createAdapter}=require('../adapters/storage/contract.js'),{broken}=require('../fixtures/synthetic/reliability.cjs');
const timestamp={generatedAt:'2030-01-01T00:00:00.000Z'};
test('snapshot checksum is deterministic integrity only; not an authenticity signature',async()=>{const a=await api.exportSnapshot(generate(),timestamp),b=await api.exportSnapshot(generate(),timestamp);assert.deepEqual(a,b);assert.equal((await api.validateSnapshot(a)).valid,true);assert.equal(a.schemaVersion,2);assert.equal(a.apiVersion,'1.0');assert.deepEqual(a.provenance.sourceIds,['SRC_SYN_001']);});
test('corrupt snapshot fails checksum and restore changes nothing',async()=>{const store=api.createMemoryStore(generate()),before=await store.read(),snapshot=structuredClone(await store.snapshot(timestamp));snapshot.records.sales[0].amount=11;assert.equal((await api.restorePreview(snapshot,store)).status,'BLOCKED');assert.equal((await store.restore(snapshot)).status,'PREVIEW_NOT_READY');assert.deepEqual(await store.read(),before);});
test('snapshot restore detects stale preview and tampering',async()=>{const store=api.createMemoryStore(generate()),snapshot=await store.snapshot(timestamp),plan=await api.restorePreview(snapshot,store),modified=structuredClone(plan);modified.baseRevision='x';assert.equal((await api.restoreSnapshot(modified,store)).status,'TAMPERED_PREVIEW');await store.delete('SalesRecord','S_SYN_002');assert.equal((await api.restoreSnapshot(plan,store)).status,'STALE_PREVIEW');});
test('snapshot schema, API, unknown fields and source provenance are validated',async()=>{for(const edit of [s=>{s.schemaVersion=3;s.records.schemaVersion=3;},s=>{s.apiVersion='2.0';},s=>{s.extra=1;},s=>{s.provenance.sourceIds=[];}]){const value=structuredClone(await api.exportSnapshot(generate(),timestamp));edit(value);const {checksum,...payload}=value;value.checksum=await u.hash(payload);assert.equal((await api.validateSnapshot(value)).valid,false);}});
test('all synthetic corruption scenarios reject before snapshot creation',async()=>{for(const kind of ['unknown-enum','future-schema','missing-field','broken-reference','unknown-field','corrupt'])await assert.rejects(api.exportSnapshot(broken(kind),timestamp),e=>e.status==='INVALID_INPUT');});
test('corrupt persisted envelope enters read-only recovery without auto reset',async()=>{let value={storageVersion:1,checksum:'bad',records:broken('corrupt')};const before=structuredClone(value),store=createAdapter({load:async()=>structuredClone(value),save:async next=>{value=structuredClone(next);return {status:'COMMITTED'};}});assert.equal((await store.recoveryStatus()).status,'RECOVERY_REQUIRED');await assert.rejects(store.read(),e=>e.status==='RECOVERY_REQUIRED');assert.equal((await store.writeAtomic(generate())).status,'RECOVERY_REQUIRED');assert.deepEqual(value,before);assert.equal((await store.exportRecovery()).integrity,'UNTRUSTED');});
test('explicit validated recovery requires current envelope fingerprint and restores data',async()=>{let value={storageVersion:1,checksum:'bad',records:broken('corrupt')};const store=createAdapter({load:async()=>structuredClone(value),save:async(next,{expectedChecksum})=>{if(value.checksum!==expectedChecksum)return {status:'STALE_PREVIEW'};value=structuredClone(next);return {status:'COMMITTED'};}}),snapshot=await api.exportSnapshot(generate(),timestamp);await store.recoveryStatus();assert.equal((await store.recover(snapshot)).status,'RECOVERY_CONFIRMATION_REQUIRED');assert.equal((await store.recover(snapshot,{expectedChecksum:'other'})).status,'STALE_PREVIEW');assert.equal((await store.recover(snapshot,{expectedChecksum:'bad'})).status,'COMMITTED');assert.equal((await store.recoveryStatus()).status,'HEALTHY');assert.deepEqual(await store.read(),generate());});
test('unsafe corrupt recovery exports refuse credential-containing payloads',async()=>{const store=createAdapter({load:async()=>({apiKey:'fake'}),save:async()=>{throw Error('Must not write');}});assert.equal((await store.exportRecovery()).status,'UNSAFE_RECOVERY_PAYLOAD');});
test('snapshot roundtrip preserves source, IDs, unknowns and completed status',async()=>{const source=generate(),store=api.createMemoryStore(api.emptyDataset()),snapshot=await api.exportSnapshot(source,timestamp);assert.equal((await store.restore(snapshot)).status,'COMMITTED');assert.deepEqual(await store.read(),source);assert.equal((await store.read()).sales[3].amount,null);assert.equal((await store.read()).activities[3].status,'completed');});
test('malformed but rechecksummed timestamps fail validation without throwing',async()=>{for(const stamp of ['2030-02-30T00:00:00.000Z','1/1/2030']){const value=structuredClone(await api.exportSnapshot(generate(),timestamp));value.generatedAt=stamp;const {checksum,...payload}=value;value.checksum=await u.hash(payload);assert.equal((await api.validateSnapshot(value)).valid,false);}});
