// SPDX-License-Identifier: Apache-2.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),api=require('../core/index.js'),{generate}=require('../generator.cjs'),{memoryAdapter}=require('../adapters/storage/contract.js');
test('memory adapter supports detached get/list plus explicit put/delete',async()=>{const store=api.createMemoryStore(generate()),row=await store.get('Hospital','H_SYN_001');row.name='Synthetic Rename';assert.notEqual((await store.get('Hospital',row.id)).name,row.name);assert.equal((await store.put('Hospital',row)).status,'COMMITTED');assert.equal((await store.list('Hospital'))[0].name,row.name);assert.equal((await store.delete('SalesRecord','S_SYN_002')).status,'COMMITTED');assert.equal(await store.get('SalesRecord','S_SYN_002'),null);});
test('critical delete rejects dangling references atomically',async()=>{const store=api.createMemoryStore(generate()),before=await store.read();assert.equal((await store.delete('Hospital','H_SYN_001')).status,'INVALID_INPUT');assert.deepEqual(await store.read(),before);});
test('multi-record mutation throws before commit without partial writes',async()=>{const store=api.createMemoryStore(generate()),before=await store.read();const result=await store.transaction(draft=>{draft.sales[0].amount=17;draft.tasks[0].status='done';throw Error('Synthetic crash');});assert.equal(result.status,'TRANSACTION_FAILED');assert.deepEqual(await store.read(),before);});
test('invalid partial transaction rejects whole draft',async()=>{const store=api.createMemoryStore(generate()),before=await store.read();assert.equal((await store.transaction(d=>{d.sales[0].amount=17;d.tasks[0].status='unknown';})).status,'INVALID_INPUT');assert.deepEqual(await store.read(),before);});
test('concurrent adapter transactions compare and swap',async()=>{const store=api.createMemoryStore(generate()),results=await Promise.all([store.transaction(d=>{d.sales[0].amount=14;}),store.transaction(d=>{d.sales[1].amount=18;})]);assert.equal(results.filter(x=>x.status==='COMMITTED').length,1);assert.equal(results.filter(x=>x.status==='STALE_PREVIEW').length,1);});
test('metadata records schema, timestamps, source and content revision',async()=>{const store=api.createMemoryStore(generate()),a=await store.metadata();assert.equal(a.schemaVersion,2);assert.equal(a.source.synthetic,true);assert.match(a.revision,/^[a-f0-9]{64}$/);assert.equal(a.createdAt,a.updatedAt);});
test('failure at backend commit leaves original bytes unchanged',async()=>{let fail=false;const store=memoryAdapter(generate(),{beforeCommit:()=>{if(fail)throw Error('Synthetic failure');}}),before=await store.read();fail=true;assert.equal((await store.transaction(d=>{d.sales[0].amount=15;})).status,'TRANSACTION_FAILED');assert.deepEqual(await store.read(),before);});
test('snapshots restore through preview rather than bypassing validation',async()=>{const store=api.createMemoryStore(generate()),snapshot=await store.snapshot({generatedAt:'2030-01-01T00:00:00.000Z'});await store.delete('SalesRecord','S_SYN_002');assert.equal((await store.restore(snapshot)).status,'COMMITTED');assert.equal((await store.list('SalesRecord')).length,4);});
test('unknown, missing, future and credential inputs cannot enter storage',async()=>{const store=api.createMemoryStore(generate()),before=await store.read();for(const edit of [d=>{d.sales[0].amount=undefined;},d=>{d.schemaVersion=3;},d=>{d.apiKey='fake';},d=>{d.tasks[0].status='unknown';}]){assert.equal((await store.transaction(edit)).status,'INVALID_INPUT');assert.deepEqual(await store.read(),before);}});
