// SPDX-License-Identifier: Apache-2.0
'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {generate}=require('../generator.cjs'),{schema1}=require('../fixtures/synthetic/reliability.cjs'),u=require('../core/state.js'),{memoryAdapter,createAdapter}=require('../adapters/storage/contract.js'),{runStorageCompatibilitySuite}=require('../adapters/storage/conformance.js');
const clock=()=> '2030-01-01T00:00:00.000Z';
test('shared storage conformance suite declares memory restart and corruption injection inapplicable',async()=>{const report=await runStorageCompatibilitySuite({name:'memory',persistence:'EPHEMERAL',dataset:generate(),legacyDataset:schema1(),createHarness:seed=>({store:memoryAdapter(seed,{clock})})});assert.equal(report.status,'PASS',JSON.stringify(report));assert.equal(report.passCount,11);assert.equal(report.notApplicableCount,2);assert.equal(report.failCount,0);assert.equal(report.cases.find(x=>x.case==='restart-persistence').status,'NOT_APPLICABLE');});
test('same conformance suite applies to retained-file fixture backend including reopening and corruption',async()=>{const report=await runStorageCompatibilitySuite({name:'synthetic-retained-file-test-backend',persistence:'RESTARTABLE',dataset:generate(),legacyDataset:schema1(),createHarness:seed=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'schedule-core-compat-')),file=path.join(dir,'head.json');let queue=Promise.resolve();const load=async()=>fs.existsSync(file)?JSON.parse(fs.readFileSync(file,'utf8')):undefined;const backend={load,save:(next,{expectedChecksum,expectedRaw})=>{const work=queue.then(async()=>{const current=await load();if((current?.checksum??null)!==expectedChecksum||expectedRaw!==undefined&&u.canonical(current)!==expectedRaw)return {status:'STALE_PREVIEW'};fs.writeFileSync(path.join(dir,'pending.json'),JSON.stringify(next));fs.renameSync(path.join(dir,'pending.json'),file);return {status:'COMMITTED',revision:next.revision};});queue=work.catch(()=>{});return work;}};const open=()=>createAdapter(backend,{seed,clock});return {store:open(),reopen:open,raw:load,corrupt:async()=>{const raw=await load();raw.checksum='0'.repeat(64);fs.writeFileSync(file,JSON.stringify(raw));},cleanup:async()=>{const resolved=fs.realpathSync(dir),expectedRoot=fs.realpathSync(os.tmpdir())+path.sep;assert.ok(resolved.startsWith(expectedRoot)&&path.basename(resolved).startsWith('schedule-core-compat-'));fs.rmSync(resolved,{recursive:true,force:true});}};}});assert.equal(report.status,'PASS',JSON.stringify(report));assert.equal(report.passCount,13);assert.equal(report.notApplicableCount,0);});
test('declaring restartable capability without reopen fails conformance instead of claiming persistence',async()=>{const report=await runStorageCompatibilitySuite({name:'incorrect-memory-capability',persistence:'RESTARTABLE',dataset:generate(),createHarness:seed=>({store:memoryAdapter(seed,{clock})})});assert.equal(report.status,'FAIL');assert.equal(report.cases.find(x=>x.case==='restart-persistence').status,'FAIL');assert.equal(report.cases.find(x=>x.case==='corruption-inspection-no-reset').status,'FAIL');});
test('conformance runner rejects unknown capability profiles and invalid private-shaped inputs',async()=>{await assert.rejects(runStorageCompatibilitySuite({dataset:generate(),persistence:'UNKNOWN',createHarness:()=>({})}),e=>e.status==='INVALID_CONFORMANCE_CONFIGURATION');const data=generate();data.synthetic=false;await assert.rejects(runStorageCompatibilitySuite({dataset:data,persistence:'EPHEMERAL',createHarness:()=>({})}),e=>e.status==='INVALID_CONFORMANCE_CONFIGURATION');});
