// SPDX-License-Identifier: Apache-2.0
'use strict';
(function(root){
 const node=typeof module==='object'&&module.exports,u=node?require('../../core/state.js'):root.ScheduleCoreV2.state,c=node?require('../../core/contracts.js'):root.ScheduleCoreV2.contracts,snap=node?require('../../core/snapshot.js'):root.ScheduleCoreV2.snapshot,migration=node?require('../../core/migration.js'):root.ScheduleCoreV2.migration;
 function demand(ok){if(!ok)throw new Error('CONFORMANCE_ASSERTION_FAILED');}
 async function runStorageCompatibilitySuite({name='synthetic-adapter',createHarness,dataset,legacyDataset,persistence}={}){
  if(typeof createHarness!=='function'||!['EPHEMERAL','RESTARTABLE'].includes(persistence)||!u.checkDataset(dataset).valid)throw new u.StateError('INVALID_CONFORMANCE_CONFIGURATION');
  const results=[],timestamp={generatedAt:'2030-01-01T00:00:00.000Z'},probe=Object.entries(c.entities).find(([,def])=>def.fields.name&&dataset[def.collection].length),empty=c.emptyDataset();if(!probe)throw new u.StateError('CONFORMANCE_NAMED_RECORD_REQUIRED');
  async function run(caseName,exercise){let harness;try{harness=await createHarness(u.clone(dataset));demand(harness?.store&&typeof harness.store.read==='function');await harness.store.read();const disposition=await exercise(harness);results.push({case:caseName,status:disposition==='NOT_APPLICABLE'?'NOT_APPLICABLE':'PASS'});}catch{results.push({case:caseName,status:'FAIL',issues:[{code:'CONFORMANCE_CASE_FAILED'}]});}finally{if(harness)try{await (harness.cleanup?harness.cleanup():harness.store.close());}catch{results.push({case:caseName+'-cleanup',status:'FAIL',issues:[{code:'CONFORMANCE_CLEANUP_FAILED'}]});}}}
  function renamed(value,name){const next=u.clone(value);next[probe[1].collection][0].name=name;return next;}
  await run('detached-reads-and-unknown-null',async({store})=>{const row=await store.get(probe[0],dataset[probe[1].collection][0].id);row.name='Synthetic Detached';const listed=await store.list(probe[0]);listed[0].name='Synthetic Detached List';demand(u.canonical(await store.read())===u.canonical(dataset));demand(await store.get(probe[0],'SYN_UNKNOWN_RECORD')===null);});
  await run('metadata-schema-identity-period-null',async({store})=>{const metadata=await store.metadata();demand(metadata.schemaVersion===2&&metadata.source.synthetic===true&&metadata.revision===await u.hash(dataset));demand(u.validTimestamp(metadata.createdAt)&&u.validTimestamp(metadata.updatedAt));demand(u.canonical(await store.read())===u.canonical(dataset));});
  await run('stable-input-and-entity-errors',async({store})=>{for(const method of ['get','list']){let rejected=false;try{await store[method]('UnsupportedEntity','SYN_UNKNOWN_RECORD');}catch(error){rejected=error.status==='UNKNOWN_ENTITY_TYPE';}demand(rejected);}demand((await store.put('UnsupportedEntity',{id:'SYN_UNKNOWN_RECORD'})).status==='UNKNOWN_ENTITY_TYPE');demand((await store.delete('UnsupportedEntity','SYN_UNKNOWN_RECORD')).status==='UNKNOWN_ENTITY_TYPE');const incomplete={id:dataset[probe[1].collection][0].id,name:'Synthetic Incomplete'};demand((await store.put(probe[0],incomplete)).status==='INVALID_INPUT');demand(u.canonical(await store.read())===u.canonical(dataset));});
  await run('duplicate-put-preserves-count-and-delete',async({store})=>{const row=u.clone(dataset[probe[1].collection][0]);row.name='Synthetic Conformance Rename';demand((await store.put(probe[0],row)).status==='COMMITTED');demand((await store.put(probe[0],row)).status==='COMMITTED');demand((await store.list(probe[0])).length===dataset[probe[1].collection].length);demand((await store.get(probe[0],row.id)).name===row.name);if(dataset.sales.length){demand((await store.delete('SalesRecord',dataset.sales[0].id)).status==='COMMITTED');demand(await store.get('SalesRecord',dataset.sales[0].id)===null);}});
  await run('transaction-thrown-rollback',async({store})=>{const before=await store.read();demand((await store.transaction(draft=>{draft[probe[1].collection][0].name='Synthetic Partial';throw Error('Synthetic Fault');})).status==='TRANSACTION_FAILED');demand(u.canonical(await store.read())===u.canonical(before));});
  await run('invalid-transaction-rollback',async({store})=>{const before=await store.read();demand((await store.transaction(draft=>{draft[probe[1].collection][0].name='Synthetic Partial';draft.schemaVersion=999;})).status==='INVALID_INPUT');demand(u.canonical(await store.read())===u.canonical(before));});
  await run('concurrent-transaction-compare-and-swap',async({store})=>{let arrived=0,release;const barrier=new Promise(resolve=>{release=resolve;});const attempts=await Promise.all(['Synthetic First','Synthetic Second'].map(name=>store.transaction(async draft=>{draft[probe[1].collection][0].name=name;if(++arrived===2)release();await barrier;})));demand(attempts.filter(x=>x.status==='COMMITTED').length===1&&attempts.filter(x=>x.status==='STALE_PREVIEW').length===1);});
  await run('stale-revision-rejects-overwrite',async({store})=>{const revision=await u.hash(await store.read());demand((await store.writeAtomic(renamed(dataset,'Synthetic Latest'),{expectedRevision:revision})).status==='COMMITTED');demand((await store.writeAtomic(dataset,{expectedRevision:revision})).status==='STALE_PREVIEW');});
  await run('snapshot-preview-roundtrip',async({store})=>{const backup=await store.snapshot(timestamp);demand((await snap.inspectSnapshot(backup)).integrityStatus==='PASS');demand((await store.writeAtomic(empty)).status==='COMMITTED');const plan=await snap.restorePreview(backup,store);demand(plan.status==='READY'&&plan.recordCount===u.datasetSummary(dataset).recordCount);demand((await snap.restoreSnapshot(plan,store)).status==='COMMITTED');demand(u.canonical(await store.read())===u.canonical(dataset));});
  await run('stale-restore-preview-rejects',async({store})=>{const backup=await store.snapshot(timestamp),plan=await snap.restorePreview(backup,store);await store.writeAtomic(renamed(dataset,'Synthetic Concurrent'));demand((await snap.restoreSnapshot(plan,store)).status==='STALE_PREVIEW');});
  await run('migration-atomic-identity-preservation',async({store})=>{if(legacyDataset===undefined)return 'NOT_APPLICABLE';const preview=await migration.migrationPreview(legacyDataset,{targetDataset:await store.read()});demand(preview.status==='READY');demand((await migration.commitMigration(preview,store)).status==='COMMITTED');const actual=await store.read();for(const def of Object.values(c.entities))demand(u.canonical(actual[def.collection].map(x=>x.id))===u.canonical(legacyDataset[def.collection].map(x=>x.id)));});
  await run('restart-persistence',async(harness)=>{if(persistence==='EPHEMERAL')return 'NOT_APPLICABLE';demand(typeof harness.reopen==='function');const changed=renamed(dataset,'Synthetic Restart');demand((await harness.store.writeAtomic(changed)).status==='COMMITTED');await harness.store.close();const reopened=await harness.reopen();demand(u.canonical(await reopened.read())===u.canonical(changed));await reopened.close();});
  await run('corruption-inspection-no-reset',async(harness)=>{if(typeof harness.corrupt!=='function'&&persistence==='EPHEMERAL')return 'NOT_APPLICABLE';demand(typeof harness.corrupt==='function'&&typeof harness.raw==='function');await harness.corrupt();const before=u.canonical(await harness.raw());demand((await harness.store.recoveryStatus()).status==='RECOVERY_REQUIRED');const report=await harness.store.inspectRecovery();demand(report.readOnly===true&&report.automaticRecovery===false&&report.partialSalvageSupported===false);demand((await harness.store.writeAtomic(dataset)).status==='RECOVERY_REQUIRED');demand(u.canonical(await harness.raw())===before);});
  return u.frozen({status:results.some(x=>x.status==='FAIL')?'FAIL':'PASS',name,persistence,cases:results,passCount:results.filter(x=>x.status==='PASS').length,notApplicableCount:results.filter(x=>x.status==='NOT_APPLICABLE').length,failCount:results.filter(x=>x.status==='FAIL').length});
 }
 const api={runStorageCompatibilitySuite};if(node)module.exports=api;else(root.ScheduleCoreV2??={}).storageConformance=api;
})(globalThis);
