// SPDX-License-Identifier: Apache-2.0
'use strict';
// Real installed engines, fresh synthetic profile per engine, no browser packages.
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),http=require('node:http'),{spawn,spawnSync}=require('node:child_process');
const source=process.env.CORE_SOURCE||path.resolve(__dirname,'..'),output=process.env.BROWSER_OUTPUT||path.join(os.tmpdir(),'schedule-core-browser-matrix-results'),engine=process.argv[2];
const suite=require(path.join(source,'tests/browser.cjs')),probe=require(path.join(source,'tests/browser-cas.cjs')),f=require(path.join(source,'fixtures/synthetic/wave1.cjs'));
const script=fs.readFileSync(path.join(source,'scripts/wave1-browser.cjs'),'utf8'),start=script.indexOf('const expression = `')+'const expression = `'.length,wave=script.slice(start,script.indexOf('`;\n',start));
const binary=(engine==='firefox'?[process.env.FIREFOX_BIN,'C:/Program Files/Mozilla Firefox/firefox.exe','/usr/bin/firefox','/usr/lib/firefox/firefox']:engine==='chromium'?[process.env.CHROME_BIN,'C:/Program Files/Google/Chrome/Application/chrome.exe','/usr/bin/google-chrome','/usr/bin/chromium']:[]).filter(Boolean).find(x=>fs.existsSync(x));
if(!binary)throw Error('Real '+engine+' executable required');fs.mkdirSync(output,{recursive:true});
const profile=fs.mkdtempSync(path.join(os.tmpdir(),'schedule-closure-'+engine+'-')),results=[];let phase,pending;
const code=()=>`(async()=>{try{for(let n=0;n<200;n++){if(globalThis.ScheduleNotesCore&&document.querySelector('#facts')?.textContent.includes('completeness'))break;await new Promise(r=>setTimeout(r,50));}let result;if(${JSON.stringify(phase)}==='cas'){result=await (${probe.toString()})();}else if(${JSON.stringify(phase)}==='wave1'){result=await ${wave};}else if(${JSON.stringify(phase)}.startsWith('crash-')){(${suite.toString()})(${JSON.stringify(phase)}).catch(e=>fetch('/result',{method:'POST',body:JSON.stringify({status:'FAIL',error:String(e)})}));for(let n=0;n<400&&!globalThis.syntheticCrashReady;n++)await new Promise(r=>setTimeout(r,25));if(!globalThis.syntheticCrashReady)throw Error('Crash timeout');result=[];}else result=await (${suite.toString()})(${JSON.stringify(phase)});await fetch('/result',{method:'POST',body:JSON.stringify({status:'PASS',phase:${JSON.stringify(phase)},userAgent:navigator.userAgent,results:result})});}catch(e){await fetch('/result',{method:'POST',body:JSON.stringify({status:'FAIL',phase:${JSON.stringify(phase)},error:String(e),stack:e.stack,userAgent:navigator.userAgent})});}})();`;
const server=http.createServer((req,res)=>{try{const p=new URL(req.url,'http://localhost').pathname;if(p==='/result'){let text='';req.on('data',d=>text+=d);req.on('end',()=>{res.end('ok');pending(JSON.parse(text));});return;}if(p==='/closure.js'){res.setHeader('Content-Type','text/javascript');res.end(code());return;}if(p==='/wave1-fixture.json'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify({dataset:f.dataset(),scope:f.scope(),buckets:f.buckets(),withdraw:f.withdraw(),archive:f.archive()}));return;}const base=path.join(source,'dist'),file=path.resolve(base,'.'+(p==='/'?'/index.html':p));if(!file.startsWith(base+path.sep)||!fs.statSync(file).isFile())throw Error('Not found');res.setHeader('Content-Type',({'.html':'text/html','.mjs':'text/javascript','.js':'text/javascript','.json':'application/json','.css':'text/css'})[path.extname(file)]||'text/plain');let data=fs.readFileSync(file);if(p==='/')data=Buffer.concat([data,Buffer.from('<script src="/closure.js"></script>')]);res.end(data);}catch{res.writeHead(404);res.end('Not found');}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));try{for(phase of(process.env.PROBE_ONLY?['cas']:['cas','seed','crash-before','crash-after','restart','wave1'])){let timer;const done=new Promise((resolve,reject)=>{pending=resolve;timer=setTimeout(()=>reject(Error(engine+' timeout '+phase)),60000);}),url='http://127.0.0.1:'+server.address().port+'/';const args=engine==='firefox'?['-headless','-no-remote','-profile',profile,url]:['--headless=new','--no-sandbox','--disable-gpu','--disable-background-networking','--disable-extensions','--disable-component-update','--no-first-run','--no-default-browser-check','--user-data-dir='+profile,url];const child=spawn(binary,args,{windowsHide:true,stdio:'ignore'});let result;try{result=await done;}finally{clearTimeout(timer);if(child.pid){if(process.platform==='win32')spawnSync('taskkill',['/PID',String(child.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});else child.kill('SIGKILL');await new Promise(r=>setTimeout(r,1000));}}results.push(result);fs.writeFileSync(path.join(output,engine+'-matrix.json'),JSON.stringify({engine,profile:'fresh synthetic only',results},null,2));console.log(JSON.stringify(result));if(result.status!=='PASS')throw Error(engine+' '+phase+' FAIL (preserved)');}}finally{server.closeAllConnections();server.close();}})().catch(e=>{console.error(e.message);process.exitCode=1;});
